version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEVICE=cpu
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - simba_network
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    mem_limit: 1g
    cpus: 0.5

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    container_name: celery_worker_cpu
    command: celery -A tasks.parsing_tasks worker --loglevel=info
    environment:
      - REDIS_HOST=redis
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEVICE=cpu
    volumes:
      - ./uploads:/app/uploads:rw
      - ./markdown:/app/markdown:rw
      - ./vector_stores:/app/vector_stores:rw
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - simba_network
    restart: on-failure
    security_opt:
      - no-new-privileges
    mem_limit: 2g
    cpus: 1

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - simba_network
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
    mem_limit: 512m
    cpus: 0.3

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    networks:
      - simba_network
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

networks:
  simba_network:
    name: simba_network
    driver: bridge

volumes:
  redis_data:
    driver: local
  ollama_data:
    driver: local 